from dotenv import load_dotenv
from os import getenv

load_dotenv()

SECRET_KEY = getenv('SECRET_KEY')
POSTGRES_USER = getenv('POSTGRES_USER')
POSTGRES_PASSWORD = getenv('POSTGRES_PASSWORD')
POSTGRES_DB = getenv('POSTGRES_DB')
POSTGRES_HOST = getenv('POSTGRES_HOST')
POSTGRES_PORT = getenv('POSTGRES_PORT')
ALGORITHM = getenv('ALGORITHM')
FRONTEND_HOST = getenv('FRONTEND_HOST')
AWS_ACCESS_KEY_ID = getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = getenv('AWS_SECRET_ACCESS_KEY')
BUCKET_NAME = getenv('BUCKET_NAME')
REGION_NAME = getenv('REGION_NAME')
SAME_SITE = getenv('SAME_SITE')
SECURE = bool(getenv('SECURE'))
ACCESS_TOKEN = 300
REFRESH_TOKEN = 7200
